CREATE TABLE [test].[Test]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(450) NOT NULL,
	[Topic] NVARCHAR(MAX) NOT NULL,
	[UserId] NVARCHAR (450) NOT NULL FOREIGN KEY REFERENCES [AspNetUsers](Id),

	CONSTRAINT [UC_NameUser] UNIQUE ([Name], [UserId])
)
