CREATE TABLE [res].[Answer]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[TaskOptionId] INT NULL FOREIGN KEY REFERENCES [test].[TaskOption](Id) ON DELETE CASCADE,
	[ResultTaskId] INT NULL FOREIGN KEY REFERENCES [res].[ResultTask](Id) ON DELETE CASCADE,
	[Value] NVARCHAR(MAX) NULL,
	[Corect] BIT NOT NULL,
	[Hash] TINYINT NOT NULL default(3),
)
